version: '3.1'
services:
  app:
    container_name: country-details-workshop
    image: acountry-details-workshop
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    links: 
      - dbpostgresql

  dbpostgresql:
    image: ghusta/postgres-world-db:2.4
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=world123
      - POSTGRES_USER=world
      - POSTGRES_DB=world-db
    volumes:
      - ./data:/var/lib/postgresql/data

